### ISSUE TITLE
Question: hypernym/hyponym tree traversal and export

### ISSUE THREAD

**Issue by dchaplinsky** [maxadamski/plwordnet#8]
Hello.

The next logical step for me is to implement tree traversal and data export.
For tree traversal I'd try to stick to the following algorithm:
- Find the true top-level hypernyms for the english and polish (no interlingual hypernymy) 
- Calculate number of leaves under each top level hypernym (and/or number of LUs under it)
- For each node calculate the distance from top-level hypernym

To export I'd like to use the information above and pass some callables for filtering to only export particular nodes/rels.
For example, I only need first 3-4 levels of the trees for nouns, that has more than X leaves. This way I'll have a way to export and visualize only parts of the trees I need.

Speaking of export, I'm looking into graphviz (to basically lay top level ontology on paper) and ttl, but in the format, that is similar to PWN original TTL export.

I'd like to have your opinion on two things:
- General approach
- How to incorporate that into code. It might be a part of Wordnet class, a separate file (maybe under contrib section), an usage example or a separate script which I/we do or don't publish at all

**Comment by maxadamski** [comment]
The general approach should work. The only annoyance will be Pythons recursion limit, so you'll have to manually keep a stack during traversal. Traversing the wordnet will probably take a long time, so I'd try to collect all stats on synsets in a single pass, and then iterate and filter the results. Also be careful when traversing synsets by following relations - I remember doing some naive traversals for relations (forget which) that I thought would form a directed acyclic graph, but sometimes my code would get into infinite loops. The data is input by hand, so there are tons of mistakes. 

I think that the `Synset` class could gain three very useful methods in the process:

- `Synset.hypernyms(transitive=False, interlinugal=False)`, which should return a set of hypernym synsets, taking into account all hypernym relations, optionally interlingual hyperonymy if you have the time to add it. One level up the tree if not transitive, and up to and including top-level if transitive.
- `Synset.hyponyms(interlingual=False)`, same, but for hyponyms (no transitive flag, because there would be too many of them for (near) top-level synsets)
- `Synset.hypernym_paths(full_search=False)`, which finds the path from a given synset to its top-level hypernym. This method should return a list of all possible hypernym paths if full_search==True, otherwise it can return one greedy path.

With these general methods you can easily express your algorithm.

I'd also like for RDF export functions to be part of the library. I'd put them in a separate file, like `plwordnet/rdf.py`.  If you will be using rdflib, maybe functions in `export.py` could be mutate a given `Graph` object by adding triples related to a specific Synset, LexicalUnit, etc., so one can choose what to export. Then the `Graph` object can be exported to TTL or other formats rdflib supports. Base triples could be defined as a multiline TTL string if its too verbose to input them programatically.

I would leave use-case specific filtering and visualizations in a separate script or even better, a Jupyter notebook, and put it in `docs` as a usage example. I'm very curious about your results :)
